import { allBooks } from './books';

export const BOOKS: allBooks[] = [
    {
        id: 1,
        title: "The World of Abstract Art",
        author: "Emily Robbins",
        published: 1984,
        category: 'art',
        cover: "https://about.canva.com/wp-content/uploads/sites/3/2015/01/art_bookcover.png",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 2,            
        title: "Paper Craft",    
        author: "Mandt Cooper",
        published: 1994,
        category: 'art',        
        cover: "https://about.canva.com/wp-content/uploads/sites/3/2015/01/creative_bookcover.png",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 3,
        title: "She Rises",    
        author: "Kate Worsley",
        published: 1974,
        category: 'romance',        
        cover: "https://i.pinimg.com/736x/9d/c3/0b/9dc30bcf29b89648aa56f882edd9569c--beautiful-book-covers-a-beautiful.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 4,
        title: "The Mothers",    
        author: "Brit Bennet",
        published: 1974,
        category: 'romance',        
        cover: "https://cdn.pastemagazine.com/www/system/images/photo_albums/30-best-book-covers-2016/large/2motherscover.jpg?1384968217",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 5,            
        title: "Troubled Daughters, Twisted Wives",    
        author: "Sara Weinman",
        published: 1974,
        category: 'romance',        
        cover: "https://i.pinimg.com/736x/fe/a5/50/fea55005c0f5bb544be91171087677e6--cover-design-magazine-penguin-book-covers.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 6, 
        title: "How to Be the Perfect Dutch",    
        author: "Kathian Brands",
        published: 1974,
        category: 'art',        
        cover: "https://spark.adobe.com/images/landing/examples/how-to-book-cover.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 7, 
        title: "1984",    
        author: "George Orwell",
        published: 1949,
        category: 'classic',        
        cover: "http://wwwcdn.printmag.com/wp-content/uploads/1984-book-covers-2.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 8, 
        title: "The Vegetarian",    
        author: "Han Kang",
        published: 1999,
        category: 'horror',        
        cover: "https://cdn.pastemagazine.com/www/system/images/photo_albums/30-best-book-covers-2016/large/2vegetariancover.png?1384968217",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 9, 
        title: "The Sea Around Us",    
        author: "Rachel L Carson",
        published: 1930,
        category: 'classic',        
        cover: "https://i.pinimg.com/736x/15/3d/7b/153d7b55365c47ef0e8f2573b3e49821--vintage-book-covers-vintage-books.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 10, 
        title: "Love Me Back",    
        author: "Merritt Tierce",
        published: 2010,
        category: 'romance',        
        cover: "https://i.pinimg.com/originals/15/a0/11/15a0115468f8ce9959ac4b9d2858184b.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 11, 
        title: "All My Puny Sorrows",    
        author: "Miriam Toews",
        published: 2015,
        category: 'comedy romance',        
        cover: "http://blog.kimhooperwrites.com/wp-content/uploads/sites/3/2015/04/book-cover-8.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 12, 
        title: "The Muse",    
        author: "Jessie Burton",
        published: 2012,
        category: 'romance fantasy',        
        cover: "https://i.pinimg.com/736x/63/b1/cd/63b1cdf5601ed7d4fb44ec14b615a44f.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 13, 
        title: "Boy, Snow, Bird",    
        author: "Helen Oyeyemi",
        published: 2013,
        category: 'romance',        
        cover: "https://images.penguinrandomhouse.com/cover/9781594633409",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 14, 
        title: "Finding Audrey",    
        author: "Sophie Kinsella",
        published: 2012,
        category: 'romance comedy',        
        cover: "http://3.bp.blogspot.com/-U79yI72pQts/VW_XnTgdTiI/AAAAAAAAL3I/yF17H1IsopI/s1600/Finding%2BAudrey%2BCover%2BJpeg.jpg",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },
    {
        id: 15, 
        title: "Vinegar Girl",    
        author: "Anne Tyler",
        published: 2014,
        category: 'romance',        
        cover: "https://i1.wp.com/www.sarahwilkins.net/wp-content/uploads/2016/04/Sarah-Wilkins-Vinegar-Girl.jpg?resize=435%2C700",
        about: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Animi dolor blanditiis nobis voluptatum commodi facilis praesentium magni aspernatur. Placeat optio molestiae consectetur quis voluptas doloremque eligendi cumque, temporibus sit. Obcaecati illum ipsam vitae ad qui, reiciendis numquam delectus nemo quae!",
    },



]